pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/my_pairs/original/suitcase"

train_data:
  video_path: "data/my_pairs/original/suitcase.mp4"
  prompt: "a man is dragging a suitcase"
  n_sample_frames: 12
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "batman is dragging a suitcase"
    - "a man is dragging a red suitcase"
    - "a man is dragging an aluminum suitcase"
    - "a man is dragging an antiqued wooden suitcase"
  video_length: 12
  width: 512
  height: 512
  num_inference_steps: 300
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 300

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True